### ISSUE TITLE
Could not find module `Gtk2HsSetup' in 0.14.2

### ISSUE THREAD

**Issue by regellosigkeitsaxiom** [gtk2hs/webkit#18]
While compiling 0.14.2 I get the following

```
webkit-0.14.2.0.log
===================
/run/user/1000/stack488/webkit-0.14.2.0/Setup.hs:5:8:
    Could not find module `Gtk2HsSetup'
    Use -v to see a list of the files searched for.
```

Meanwhile `webkit-0.14.1` compiles just fine

**Comment by hamishmack** [comment]
Were you using stack or cabal?  Which version?  What was the command line you used to install?

**Comment by regellosigkeitsaxiom** [comment]
Command line: `stack --nix build`
```
$ stack --version
Version 1.0.2 x86_64
```
```
stack.yaml
==========
flags: {}
nix:
  enable: false
  packages:
  - haskellPackages.gtk2hs-buildtools
  - haskellPackages.happy
  - haskellPackages.alex
  - pkgconfig
  - webkitgtk2
  - glib
  - cairo
  - pango
  - gtk
extra-package-dbs: []
packages:
- '.'
extra-deps:
- text-1.2.2.1
- webkit-0.14.2.0
resolver: lts-5.9
```
